### ISSUE TITLE
mac 10.15 Beta not work

### ISSUE THREAD

**Issue by KorolZhu** [DeVaukz/MachO-Explorer#2]
mac 10.15 Beta not work

**Comment by anonymouz4** [comment]
Doesn't work on the official release of 10.15 too

**Comment by DeVaukz** [comment]
Doesn't compile or crashes?

**Comment by anonymouz4** [comment]
It compiles but no window opens when running. The applications becomes active when launching (the menu bar becomes visible), but even if I try to manually open any mach-o file, no window appears
